name: Create iOS Release Build

on:
  workflow_call:
    inputs:
      targetName:
        required: true
        type: string
      workspaceName:
        required: true
        type: string
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Env: \"${{ inputs.targetName }}\""
        echo "Env: ${{ inputs.workspaceName }}"
      
    - name: List of simulator
      run: xcrun simctl list

    - name: Open simulator
      run: open -a Simulator --args -CurrentDevice UDID E7358E62-ECF9-436A-834F-CFB7C2801FD9
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Install Pods
      run: pod install
      shell: bash

    - name: Clean and Build
        uses: .github/workflows/iOSBasicSharedActionCleanAndBuild.yml
            with:
                targetName: POC_GithuAction
                workspaceName: POC_GithuAction.xcworkspace

    - name: Test
        uses: .github/workflows/iOSBasicSharedActionTesting.yml
            with:
            targetName: POC_GithuAction
            workspaceName: POC_GithuAction.xcworkspace
      
