name: Create iOS Release Build

on:
  workflow_call:
    inputs:
      targetName:
        required: true
        type: string
      workspaceName:
        required: true
        type: string
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - name: Checkout Project repo
      uses: actions/checkout@v3
    - name: Checkout shared actions repo
      uses: actions/checkout@v3
      with:
        repository: mohanraajsk/POC_Shared_Actions
        path: sharedrepo
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Install Pods
      run: pod install
      shell: bash
      
    - name: Pod Integrity Stage
      id: pod_status
      run: |
           pwd
           ls
           mkdir -p ./build/
                   ./sharedrepo/DevOps/ci/script/check-pods-integrity.swift ${{ inputs.targetName }} > pod_integrity.txt
           echo "::set-output name=pod_status::success"

      
